name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Bump minor version
        id: bump_version
        run: |
          current_version=$(jq -r .version package.json)
          # Extract major, minor, and patch versions
          IFS='.' read -r -a version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          # Increment minor version and reset patch version
          minor=$((minor + 1))
          new_version="$major.$minor.0"
          # Update package.json with the new version
          jq ".version = \"$new_version\"" package.json > package.tmp.json
          mv package.tmp.json package.json
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit and push version bump
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m "chore: bump version to ${{ env.new_version }}"
          git push https://$PAT@github.com/${{ github.repository }}.git HEAD:master